### ISSUE TITLE
Sign-in Flow API Call

### ISSUE THREAD

**Issue by haunguyen90** [kodiakorg/financial#10]
Ref: #3 
## Todo
  - [x] Step 1: Call API with email attached in the payload to check the email in the db
  - [x] Step 2: Call API with email & password to login
  - [x] Step 3: Call API with verification number to verify the user
  - [x] Store the token into redux and use it for every further API call after logged in (https://github.com/kodiakorg/financial-planning-dashboard/blob/master/src/utils/apiUtils.ts#L29)
  - [x] Check the token's expired time and refresh to get the new token if the token is expired
  - [x] Check auth and redirect the user to `/sign-in` screen if the user is not logged in
