### ISSUE TITLE
Formik Implementation

### ISSUE THREAD

**Issue by haunguyen90** [kodiakorg/financial#11]
Ref: #3 
## Todo
 - [x] Use Formik for building form handling
 - [x] Build all base form elements/components for global usage such as input, button, checkbox, dropdown,.. using Formik
 - [x] Implement form validation & error/warning
