### ISSUE TITLE
Convert and styling Screen 3.3 (HTML/CSS/Animation)

### ISSUE THREAD

**Issue by haunguyen90** [kodiakorg/financial#12]
Ref: #4 

## Todo
 - [x] Main layout
 - [x] Header: we will have to reduce the width of the search bar (not full screen like the UI design). The search header will be placed just on the right content, not full screen
[See attached image](https://github.com/kodiakorg/financial/issues/12#issuecomment-477425048)
 - [x] Left side bar
      ```
         Make sure we can “collapse” this left hand menu like here:
         https://ant.design/components/menu/#components-menu-demo-inline-collapsed
      ```
    - [x] User info
        ```
           The main entries like "John Samual" should be expandable and collapsable (like in a standard mail client)
           Expanding should: show the sub entries and their tags
           Collapsing should: hide the sub entries and their tags
           Use animation from ant collapse - https://ant.design/components/menu/#components-menu-demo-inline
        ```
    - [x] Active Effect on the client full name (collapse expanded)
    - [x] Statuses
         ```         
             Use the ant default "preset style" for the tags in the LHS subentries
             So the text colour will be slightly darker than the tag colour
             https://ant.design/components/tag/#components-tag-demo-colorful
             Here are the colour codes to use for tags:
               - Position [#E9472E]
               - Strategy [#E4A140]
               - Products [#F9CC4C]
               - Advice [#9EC341]
               - Done [#4A9F45]
          ```
 - [x] Main content (with different background image): When select client from the left menu, the background image should be changed (Screen 3.3) with text: `Hi John we missed you....`
 - [x] Float button at bottom left screen - New client button (3.3)
 - [x] Float button at bottom right screen - Plus button (3.3)
 - [x] Hover effects on user info (screen 3.3)
 - [x] Click effects for float buttons

**Comment by haunguyen90** [comment]
![image](https://user-images.githubusercontent.com/8245883/55126160-cb2c2180-513e-11e9-922d-7d1f33fb6648.png)
