### ISSUE TITLE
Convert Step by Step modals 4.0 - 4.3

### ISSUE THREAD

**Issue by haunguyen90** [kodiakorg/financial#14]
Ref: #5 

## Todo:
 - [x] Screen 4.0 - Component name: NameAndBirthDay
 - [ ] Screen 4.1 - Component name: WhoNeedsAdvice
 - [ ] Screen 4.2 - Component name: TellUsYourPartner
 - [ ] Screen 4.3 - Component name: YourOccupation

## Expected
 - [ ] Each button should have hover & click effects like in this [example](https://www.dropbox.com/s/tlbzlzxkupyog5x/button%20clicked%20effect.mp4?dl=0)

**Comment by sdharmarajah** [comment]
@vienpn91 please do not start this task - there is a change here

**Comment by haunguyen90** [comment]
Hi @sdharmarajah, This task is just for implementing the static HTML/CSS/Animation for the modals, the scope is just limited in the UI. 
The UX flow & functionalities will be raised in the other tickets
