### ISSUE TITLE
Implement layout structure for the right side content (cont) - Implement layout structure for the data entry tables

### ISSUE THREAD

**Issue by dinhnguyentrunghoa** [kodiakorg/financial#30]
Ref: #22 

## Before
  Please check the attached image for more information about the input type for each cell
 Refer: https://xd.adobe.com/view/f23bfc14-efb0-479c-5357-593c060c1153-840a/screen/4edc8772-5049-44e4-b5a2-8c8a8e03904d/Web-1366-13?fullscreen
 
## TODO
   - [ ] Table styling: Title, Table head, Row & Column content, Fixed Action column
   - [ ] Config column for all data entry tables
   - [x] Every row will have its `expandable` section **[Indra: Not every row - just rows that have the "small plus" icon on the LHS]**. **This is also a native component:** https://ant.design/components/table/#components-table-demo-expand
   - [x] Add Function, click on the `+` icon 
   - [x] Delete button in the Action column: let's go with the "pop confirm" dialog here
https://ant.design/components/popconfirm/#components-popconfirm-demo-icon

`Note: Please ignore the horizontal cards on the top of the right content.`

[ ] Use [this](https://motion.ant.design/exhibition/demo/table-enter-leave) animation for adding and deleting row.

![56552285-70081600-65a8-11e9-99b4-669c0f2c47b3](https://user-images.githubusercontent.com/8245883/56553459-c3826000-65b8-11e9-95dd-447ee54a24c2.png)

**Comment by moewiz** [comment]
By default, ant design does not support `expand` and `scroll` at the same table. For now, the table only supports one of them at one time. 

![warning](https://user-images.githubusercontent.com/12948375/56709203-2820f480-674a-11e9-920d-7695507125d1.png)

![test](https://user-images.githubusercontent.com/12948375/56709303-b4cbb280-674a-11e9-8cb6-c86c89e48cf8.png)

**Comment by moewiz** [comment]
First, I implement the expand function. The scroll function will fix later.

**Comment by moewiz** [comment]
Hi @sdharmarajah, we have encountered a couple of problems as I comment above. To make these two functions work compatible, we may have to override the style of the table. It seems to take more time and I have to inform you.

**Comment by sdharmarajah** [comment]
Hi @moewiz 
Then please pause this task until we discuss
We prefer to use native as much as possible (no overriding) 
Let's coordinate a time to discuss
