### ISSUE TITLE
Data entry tables: Assets

### ISSUE THREAD

**Issue by dinhnguyentrunghoa** [kodiakorg/financial#31]
Ref: #22 

## Before
  Please check the attached image for more information about the input type for each cell

## TODO
This is the most complicated table. We have the child table in a table
- [x] Prepare the layout for this table. Include all the child table.
- [x] Using HOC component (already defined in #29) to apply all the cell of table
- [x] Implement the delete function
- [x] Implement the add function

 [ ] Use [this](https://motion.ant.design/exhibition/demo/table-enter-leave) animation for adding and deleting row.

![56552285-70081600-65a8-11e9-99b4-669c0f2c47b3](https://user-images.githubusercontent.com/8245883/56553459-c3826000-65b8-11e9-95dd-447ee54a24c2.png)
