### ISSUE TITLE
Convert Step by Step modals from designs to static React Components

### ISSUE THREAD

**Issue by haunguyen90** [kodiakorg/financial#5]
Design: https://gallery.io/projects/MCHbtQVoQ2HCZZtcns12mvPd/files/MCHbtQVoQ2HCZWmDlkklwV_I

## Tasks:
 - Convert Step by Step modals 4.0 - 4.3 (#14)
 - [ ] Screen 4.4
 - [ ] Screen 4.5
 - [ ] Screen 4.6
 - [ ] Screen 4.7
 - [ ] Screen 4.8

## Expected
 - [ ] 2 buttons on the bottom left should be Cancel & Next if the current screen **IS NOT** the last step in the flow
 - [ ] 2 buttons on the bottom left should be Cancel & DONE if the current screen **IS** the last step in the flow
 - [ ] Screen 4.1 - If the selected is  `Me` ---GoTo--> 4.3 ---> 4.5 ---> 4.6 ---> 4.7
 - [ ] Screen 4.1 - If the selected is  `Couple` ---GoTo--> 4.2 ---> 4.3 ---> 4.4 ---> 4.5 ---> 4.6 ---> 4.7 ---> 4.8
 - [ ] Each button should have hover & click effects like in this [example](https://www.dropbox.com/s/tlbzlzxkupyog5x/button%20clicked%20effect.mp4?dl=0)

**Comment by sdharmarajah** [comment]
To discuss: Animation effect in modals. Look at hover effect from original video. Agree to always review the Turbotax video before finalising anything that's already there

**Comment by sdharmarajah** [comment]
As discussed on Thursday 21st morning call: 
- wait for Hau to share example of what the transition will be (from modal -> modal)
- change the mouse icon on hover, to indicate the image button in the modal is clickable

**Comment by sdharmarajah** [comment]
@hau please don't work on this until I update you on one thing

Basically we need to break this into 2 API calls, not one

**Comment by sdharmarajah** [comment]
@haunguyen90 
Please see the "broken into 2 API" screens attached:

"4.0-part1.png" -> "4.0-part2.png" -> "4.1.png"


- Make the 1st API call (to create a client: something like `[POST] /client`) when the user clicks "Done" on "4.0-part1.png"

- Proceed with the already discussed flow, when user clicks the plus button on "4.0-part2.png"


![4 0-part1](https://user-images.githubusercontent.com/8509047/54899159-ef94bd80-4ef4-11e9-8907-6bd17904bb96.png)
![4 0-part2](https://user-images.githubusercontent.com/8509047/54899160-ef94bd80-4ef4-11e9-94bc-0bc6beae53ce.png)
![4 1](https://user-images.githubusercontent.com/8509047/54899161-ef94bd80-4ef4-11e9-97cf-5059cd6f64b5.png)

**Comment by sdharmarajah** [comment]
Hi @haunguyen90 

As discussed today (March 25) on Slack please break this into smaller tasks

Since there is a common template (modal with buttons) I assume we can deliver this efficiently (time, code, etc)

Ping me when you want me to review, thanks

**Comment by sdharmarajah** [comment]
@haunguyen90 @moewiz @vienpn91  please do not start this task - there is a change here
