### ISSUE TITLE
Create the drawer page

### ISSUE THREAD

**Issue by dinhnguyentrunghoa** [kodiakorg/financial#61]
#40 
## TODO
- [x] Click on the graph -> Show the drawer
- [x] Click outside -> Close the drawer
- [x] Create the layout of a drawer. (Header, main content, footer)
- [x] Tabs for client and partner
- [x] Basic layout of the table.

![pull-out-drawer-big](https://user-images.githubusercontent.com/16713398/60161022-d87da880-9820-11e9-8b37-dc09e6ee62e7.png)
