### ISSUE TITLE
Create the drawer page (cont)

### ISSUE THREAD

**Issue by dinhnguyentrunghoa** [kodiakorg/financial#62]
#40 
## TODO
- [x] Expand/collapse function
- [x] Editable row + Bold text 
- [x] Implement the pagination function
![pull-out-drawer-big](https://user-images.githubusercontent.com/16713398/60161286-71acbf00-9821-11e9-8953-87eac50b1451.png)
