### ISSUE TITLE
Implement redux flow to fetch drawer JSON data to redux store 

### ISSUE THREAD

**Issue by dinhnguyentrunghoa** [kodiakorg/financial#63]
#40
## TODO
- [x] Define actions for handling fetching data for the drawer.
- [x] Create Drawer service provide the function to fetching data from the JSON file.
- [x] Describe saga flow for handling fetching data.
- [x] Reducer handle actions and store data to redux.
