### ISSUE TITLE
Pour drawer data from redux store to drawer component

### ISSUE THREAD

**Issue by dinhnguyentrunghoa** [kodiakorg/financial#64]
#40
## TODO
- [x] Get all data from redux store to drawer component
- [x] Pour data to the header and footer of the drawer
- [x] Send data to the client tab and partner tab
- [x] Init the number of columns
- [x] Init the pagination section based on the number of pages.
