### ISSUE TITLE
Convert and styling Sign-in screens (HTML/CSS/Animation)

### ISSUE THREAD

**Issue by haunguyen90** [kodiakorg/financial#8]
Ref: #3 
Sign-in flow starts from screen 1.0 to 2.2
## Todo
 - [x] Create LoginLayout & background
 - [x] Modify Ant `Header`, `Header Item` to make it match with the design
 - [x] Import and using fontawesome React
 - [x] Implement Static Login Form (3 Steps: Email --> Password --> Verification)
 - [x] Modify & override Ant `Input`, `Button`, & `Form Elements` to export our own elements for further using.
 - [x] Modal transition - Slide from right to left when go the next step of the form
 - [x] Input placeholder transition to top when focus
 - [x] Form error/warning displays
