### ISSUE TITLE
Sign-in - Code & Logic flow implementation

### ISSUE THREAD

**Issue by haunguyen90** [kodiakorg/financial#9]
Ref: #3 

## Todo
 - [x] Screen 2.0 - focus (cursor) should go to the first input box & submit button will be disabled as default
 - [x] Screen 2.0 - after entering every single number into the next input box, it should automatically go to the next input box
 - [x] Screen 2.0 - After entering 4 numbers, the submit button will be submitted automatically
 - [x] Screen 2.0 - During the submitting, the submit button should be displayed with loading indicator - see example [here](https://ant.design/components/modal/#components-modal-demo-async)
 - [x] Hover effects for inputs, buttons
 - [x] Click effects for buttons
 - [x] Modal loading when calling API - https://ant.design/components/modal/#components-modal-demo-async
